### ISSUE TITLE
Stuck at Selected Security Scheme

### ISSUE THREAD

**Issue by zacknewman** [any1/wlvncc#21]
When using `wlvncc` to connect to a VNC server, I see the following output in Alacritty:
```
Using EGL for rendering...
20/12/2022 19:04:21 VNC server supports protocol version 3.8 (viewer 3.8)
20/12/2022 19:04:21 We have 1 security types to read
20/12/2022 19:04:21 0) Received security type 2
20/12/2022 19:04:21 Selecting security type 2 (0/1 in the list)
20/12/2022 19:04:21 Selected Security Scheme 2

```
After that, it just hangs; and I have to go into a different `sway` workspace to kill it. I would not be surprised if there are missing dependencies as I have a fairly minimal Arch Linux setup, but I did make sure to install all the runtime dependencies mentioned here. Do you have any insight on what the problem may be?

**Comment by manio** [comment]
Hi!
I have exactly same problem as @zacknewman.

I've bisected the problem and the problematic commit is:
[232bcad Remove vncrec suppport](https://github.com/any1/wlvncc/commit/232bcadd4acca9c2d864b2679a12f7d810db19a7)

When reverting this commit on top of master (and resolving one conflict) then it works as expected:
Instead of stucking, it is asking me for a password and connecting afterwards.

Additional info:
```Server "unknown (LibVNCServer 0.9.13)"```

Steps to reproduce: install eg DroidVNC-NG on your android phone and try to connect to it...
